name: Build

on:
  # Run any time a commit is pushed to certain branches
  push:
    branches: [ "main" ]

  # Allow you to run the workflow manually from Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: psuedo build
        run: echo Build

      - name: ServiceNow DevOps Register Artifact
        uses: ServiceNow/servicenow-devops-register-artifact@v5.1.0
        with:
            devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            job-name: ServiceNow DevOps Register Artifact
            context-github: ${{ toJSON(github) }}
            artifacts: '[{"name": "githubActionsArtifact","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'                      
