# name: Deploy

# on:
#   workflow_run:
#     workflows: ["Build"]
#     branches: [main]
#     types: 
#       - completed

#   workflow_dispatch:

# jobs:
#   register_package:
#     name: Register Package
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     steps:
#       - name: ServiceNow DevOps Register Package
#         uses: ServiceNow/servicenow-devops-register-package@v5.1.0
#         with:
#           devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
#           instance-url: ${{ secrets.SN_INSTANCE_URL }}
#           tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
#           context-github:  ${{ toJSON(github) }}
#           artifacts: '[{"name": "sn-devops-change-velocity-art","version": "1.${{ github.event.workflow_run.run_number }}","semanticVersion": "1.${{ github.event.workflow_run.run_number }}.0","repositoryName": "${{ github.repository }}"}]'                                # Name of the Package that contains list of artifacts
#           package-name: 'sn-devops-change-velocity-pkg'
#           job-name: 'Register Package'

#   uat_pre_deploy:
#     name: UAT PreDeploy
#     runs-on: ubuntu-latest
#     needs: register_package
#     steps:
#       - name: ServiceNow DevOps Change Automation
#         uses: ServiceNow/servicenow-devops-change@v6.1.0
#         with:
#           instance-url: ${{ secrets.SN_INSTANCE_URL }}
#           devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
#           tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
#           job-name: 'UAT PreDeploy'
#           context-github: ${{ toJSON(github) }}
#           change-request: '{"setCloseCode":"true","autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
#           abortOnChangeCreationFailure: true
#           deployment-gate: '{"environment":"UAT","jobName":"UAT Deploy"}'

#   uat_deploy:
#     name: UAT Deploy
#     runs-on: ubuntu-latest
#     needs: uat_pre_deploy
#     environment: UAT
#     steps:
#       - name: Deploy me
#         run: echo Deployed

#   prod_pre_deploy:
#     name: Prod PreDeploy
#     runs-on: ubuntu-latest
#     needs: uat_deploy
#     steps:
#       - name: ServiceNow DevOps Change Automation
#         uses: ServiceNow/servicenow-devops-change@v6.1.0
#         with:
#           instance-url: ${{ secrets.SN_INSTANCE_URL }}
#           devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
#           tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
#           job-name: 'Prod PreDeploy'
#           context-github: ${{ toJSON(github) }}
#           change-request: '{"setCloseCode":"true","autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
#           abortOnChangeCreationFailure: true
#           deployment-gate: '{"environment":"Production","jobName":"Production Deploy"}'
          
#   prod_deploy:
#     name: Production Deploy
#     runs-on: ubuntu-latest
#     needs: prod_pre_deploy
#     environment: Production
#     steps:
#       - name: Deploy me
#         run: echo Deployed
